### ISSUE TITLE
Retraction operation

### ISSUE THREAD

**Issue by blup-Blupon** [adavoudi/spdnet#10]
Hi,

I'm new to geometric deep learning and I'm wondering why you chose to realize the retraction operation with:
```
data = A + ref
Q, R = data.qr()
sign = (R.diag().sign() + 0.5).sign().diag()
out = Q.mm(sign)
```
instead of

```
data = A + ref
Q, R = data.qr()
out = Q
```
as is suggested in equation 4.8 page 59 of [Optimization Algorithms on Matrix Manifolds](http://www.eeci-institute.eu/GSC2011/Photos-EECI/EECI-GSC-2011-M5/book_AMS.pdf) (Absil, Mahony, Sepulchre), which is the reference of the original SPDNet paper for this exact operation.

In any case, I take advantage of this post to thank you for your public PyTorch implementation of the paper !

Cheers,
Blupon.

**Comment by adavoudi** [comment]
Hi,
Just to avoid negative values in the output matrix.

Best,

**Comment by blup-Blupon** [comment]
Thank you for your answer. Could you be more accurate regarding your motivation to choose this specific way to avoid negative values please (why use `R`) ? For example, you could have just added `abs(min(Q))` to the whole matrix if I'm not mistaken.

Sorry if this question stems from insufficient knowledge of applied maths.

**Comment by adavoudi** [comment]
I think the main reason was to make my outputs compatible with the original Matlab implementation. Maybe there is a difference in the implementation of the QR decomposition between Matlab and PyTorch. 

Anyway, it was the only approach to reproduce the original paper's results. However, I think what you mentioned is also totally correct.

**Comment by blup-Blupon** [comment]
Okay, that answers my question. Thanks again !
