### ISSUE TITLE
mat file for running examples/demo.py

### ISSUE THREAD

**Issue by alekseic** [adavoudi/spdnet#3]
Hello,
Many thanks for your Riemannian network for SPD matrices implementation! 
How do you obtain spddb_afew_train_spd400_int_histeq.mat ?
I downloaded AFEW SPD data from Zhiwu Huang's website at ETH, but I don't know how to process the many SPD matrices in order to get your demo.py running.

**Comment by adavoudi** [comment]
Have you found it?! 

If not, I can upload it. It's about 1.5 Gigabyte.

**Comment by alekseic** [comment]
I didn't find the file itself. It's not that important now, I'm working on another project with my own data, I just wanted to check if your code works, so I thought to try and test it on this problem. I think, it's better to post a web link or a script for either downloading it, or constructing it from Zhiwu Huang's many mat files. So anyone who **really** needs it could get it.

**Comment by raj-shah** [comment]
I believe the mat file exists in the [author's repo](https://github.com/zzhiwu/SPDNet/tree/master/data/afew).

**Comment by adavoudi** [comment]
I added a script for downloading the data. It will download the data if it does not already exist.
