### ISSUE TITLE
size of weights of SPDTransform incorrect when dimension increases

### ISSUE THREAD

**Issue by alekseic** [adavoudi/spdnet#6]
Hi again,
I have a neural net with these modules:

self.trans1 = SPDTransform(52, 26)
self.trans2 = SPDTransform(26, 13)
self.trans3 = SPDTransform(13, 26)
self.trans4 = SPDTransform(26, 52)

When I take a look at my model.trans3.weight.shape, I norice that it is torch.Size([26, 26]), and model.trans4.weight.shape returns torch.Size([52, 52]). I don't know how this is treated in the code, but it seems to be a mistake. For trans1 and trans2, i.e. when dimenstion decreases, the shape of the weights is correct.

**Comment by alekseic** [comment]
Hi, 
Could you please comment why do you make the weights a square matrix, whenever the dimension increases in SPDIncreseDim. Could it be an error?

**Comment by adavoudi** [comment]
@alekseic no it was intentionally. The fact is that I have not seen any paper who uses a transform which increases the dimension. This is especially difficult when we are dealing with SPD matrices and we need them to stay SPD after the transformation. What I did was to copy the source matrix into the upper right corner of an identity matrix with the desired size. The procedure is more clear in the code.  

Also, if you have any idea for increasing the dimension of a SPD matrix while preserving its positive definiteness, please share it.

**Comment by alekseic** [comment]
I found a similar question here: 
https://math.stackexchange.com/questions/2527201/any-way-to-map-a-symmetric-positive-definite-matric-to-another-one-with-larger-d
They suggest to put the matrix into the upper *left* corner and fill the rest with "eye".

**Comment by adavoudi** [comment]
Yeah. It is exactly what I did.
