### ISSUE TITLE
Missing SPDTransformFunction

### ISSUE THREAD

**Issue by afalaize** [adavoudi/spdnet#7]
Hi;
We are facing an error when runing the tests/test_modules.py.
A (torch.autograd.)Function is missing (not defined): Although the nn.Module `SPDTransform`  is well defined, we can not find the `SPDTransformFunction`.
Is it a critical issue or the remaining of the code can be executed without difficulties?
Best regards;
A. Falaize

**Comment by adavoudi** [comment]
Hi,
What's your PyTorch version?

**Comment by afalaize** [comment]
Hi;
The error we were facing just... gone.
I don't see which commit removed the call to `SPDTransformFunction`, but the tests are passing now with the current master.
Best regards;
Antoine
